# Generated by Django 3.2 on 2021-04-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField(blank=True)),
                ('Qualification', models.CharField(max_length=15)),
                ('StaffId', models.TextField(blank=True)),
                ('IDcard', models.ImageField(upload_to='provider/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Additem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Provider', models.CharField(max_length=30)),
                ('GSTNo', models.CharField(max_length=15)),
                ('Comment', models.TextField(blank=True)),
                ('Bill', models.ImageField(upload_to='provider/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
