# Generated by Django 3.1.1 on 2021-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='Bill',
        ),
        migrations.AlterField(
            model_name='additem',
            name='Quantity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='additem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addstaff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
