# Generated by Django 3.2 on 2021-04-19 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatitentName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField(blank=True)),
                ('DrugName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Comment', models.TextField(blank=True)),
                ('Prescription', models.ImageField(upload_to='Patitent/images')),
                ('Orderno', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
