# Generated by Django 3.2 on 2021-04-19 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patitent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderdeatils',
            new_name='Orderdetails',
        ),
    ]
